# Generated by Django 3.0.5 on 2020-09-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demand_draft',
            fields=[
                ('dd_no', models.IntegerField(primary_key=True, serialize=False)),
                ('dd_name', models.CharField(max_length=20)),
                ('dd_bank', models.CharField(max_length=20)),
                ('dd_amount', models.IntegerField()),
                ('dd_date', models.DateTimeField()),
            ],
        ),
    ]
