# Generated by Django 3.0.5 on 2020-09-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='number_register',
            fields=[
                ('mob_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
