# Generated by Django 3.0.5 on 2020-09-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0002_number_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('yojna', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=30)),
                ('mobile_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catlog.number_register')),
            ],
        ),
    ]
