# Generated by Django 3.1.1 on 2020-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0004_auto_20200926_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand_draft',
            name='dd_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
