# Generated by Django 3.0.5 on 2021-03-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0006_customer_detain'),
    ]

    operations = [
        migrations.CreateModel(
            name='kit_numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custmer_id', models.IntegerField()),
                ('customer_account', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='customer_detain',
            new_name='customer_detail',
        ),
    ]
