# Generated by Django 3.0.5 on 2021-03-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0007_auto_20210315_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kit_numbers',
            old_name='custmer_id',
            new_name='customer_id',
        ),
        migrations.AddField(
            model_name='kit_numbers',
            name='welcome_kit_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
