# Generated by Django 3.0.5 on 2021-03-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0009_auto_20210315_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='debitCard',
            fields=[
                ('debit_card_kit', models.IntegerField(primary_key=True, serialize=False)),
                ('debit_card_number', models.IntegerField()),
            ],
        ),
    ]
